            $(document).ready(function(){
                $("#EEE").click(function(){
                    $("#EEEMenu").toggle("slow");
                    $("#ECEMenu").hide();
                    $("#CSEMenu").hide();
                    $("#MECHMenu").hide();
                    $("#CVLMenu").hide();
                    $("#CEMenu").hide();
                    $("#MMEMenu").hide();
                });
                $("#ECE").click(function(){
                    $("#ECEMenu").toggle("slow");
                    $("#EEEMenu").hide();
                    $("#CSEMenu").hide();
                    $("#MECHMenu").hide();
                    $("#CVLMenu").hide();
                    $("#CEMenu").hide();
                    $("#MMEMenu").hide();
                });
                $("#CSE").click(function(){
                    $("#CSEMenu").toggle("slow");
                    $("#ECEMenu").hide();
                    $("#EEEMenu").hide();
                    $("#MECHMenu").hide();
                    $("#CVLMenu").hide();
                    $("#CEMenu").hide();
                    $("#MMEMenu").hide();
                });
                $("#MECH").click(function(){
                    $("#MECHMenu").toggle("slow");
                    $("#ECEMenu").hide();
                    $("#CSEMenu").hide();
                    $("#EEEMenu").hide();
                    $("#CVLMenu").hide();
                    $("#CEMenu").hide();
                    $("#MMEMenu").hide();
                });
                $("#CVL").click(function(){
                    $("#CVLMenu").toggle("slow");
                    $("#ECEMenu").hide();
                    $("#CSEMenu").hide();
                    $("#MECHMenu").hide();
                    $("#EEEMenu").hide();
                    $("#CEMenu").hide();
                    $("#MMEMenu").hide();
                });
                $("#CE").click(function(){
                    $("#CEMenu").toggle("slow");
                    $("#ECEMenu").hide();
                    $("#CSEMenu").hide();
                    $("#MECHMenu").hide();
                    $("#CVLMenu").hide();
                    $("#EEEMenu").hide();
                    $("#MMEMenu").hide();
                });
                 $("#MME").click(function(){
                    $("#MMEMenu").toggle("slow");
                    $("#ECEMenu").hide();
                    $("#CSEMenu").hide();
                    $("#MECHMenu").hide();
                    $("#CVLMenu").hide();
                    $("#CEMenu").hide();
                    $("#EEEMenu").hide();
                });
            });